# Generated by Django 4.2.17 on 2024-12-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новину', 'verbose_name_plural': 'Новини'},
        ),
    ]
