# Generated by Django 4.2.17 on 2025-01-20 17:32

import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='content_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content_type',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
    ]
