# Generated by Django 4.2.17 on 2025-01-20 17:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsitem_content_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='content_file',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Файл контента'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content_type',
            field=models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео')], max_length=10, verbose_name='Тип контенту'),
        ),
    ]
