# Generated by Django 4.2.17 on 2024-12-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Інформація')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Відео')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Назва події')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
            },
        ),
    ]
