# Generated by Django 4.2.17 on 2025-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Головна Інформація')),
                ('image', models.ImageField(upload_to='main/', verbose_name='Зображення')),
                ('name', models.CharField(max_length=155, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Інформацію',
                'verbose_name_plural': 'Інформація',
            },
        ),
        migrations.CreateModel(
            name='MainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Головна Назва блоку')),
                ('video', models.FileField(upload_to='main/', verbose_name='Відео')),
                ('detail_url', models.URLField(blank=True, null=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блок',
            },
        ),
    ]
