# Generated by Django 4.2.17 on 2025-01-20 10:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
    ]
