# Generated by Django 4.2.17 on 2025-01-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='detail_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання'),
        ),
    ]
