# Generated by Django 4.2.17 on 2025-01-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Презентація')),
                ('image', models.ImageField(upload_to='present/', verbose_name='Зображення')),
                ('description', models.CharField(max_length=255, verbose_name='')),
                ('file_present', models.FileField(upload_to='ol/', verbose_name='Файл для скачування')),
            ],
            options={
                'verbose_name': 'Презентацію',
                'verbose_name_plural': 'Презентація',
            },
        ),
    ]
