# Generated by Django 4.2.17 on 2025-01-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsInform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Останні події (Документи)')),
                ('image', models.ImageField(upload_to='documents/', verbose_name='Зображення')),
                ('name', models.CharField(max_length=155, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Подію',
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='DocumentsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Найменування')),
                ('image', models.ImageField(upload_to='documents/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Презентація (Про нас)'),
        ),
    ]
