# Generated by Django 4.2.17 on 2025-01-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_reviewsinfo_reviewsitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsinform',
            options={'verbose_name': 'Подію', 'verbose_name_plural': 'Документи Події'},
        ),
        migrations.AlterModelOptions(
            name='reviewsinfo',
            options={'verbose_name': 'Сервіс', 'verbose_name_plural': 'Відгуки Сервіс'},
        ),
    ]
