# Generated by Django 4.2.17 on 2025-01-20 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_reviewsitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsinform',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='documentsitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file_present',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Файл для скачування'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='reviewsinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='reviewsitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
    ]
