# Generated by Django 4.2.17 on 2024-12-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransformItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Серія')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Зображення')),
                ('detail_url', models.URLField(blank=True, null=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Серію',
                'verbose_name_plural': 'Новини',
                'db_table': 'transform',
            },
        ),
    ]
