# Generated by Django 4.2.17 on 2024-12-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_informtransform_alter_transformitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformTm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Потужність трансформаторів ТМ та ТМЖ')),
                ('image', models.ImageField(upload_to='img_tm/', verbose_name='Креслення трансформаторів ТМ та ТМЖ')),
                ('file_tm', models.FileField(upload_to='drawing_tm/', verbose_name='Скачати креслення трансформаторів ТМ та ТМЖ')),
            ],
            options={
                'verbose_name': 'Трансформатор ТМ та ТМЖ',
                'verbose_name_plural': 'Трансформатори ТМ та ТМЖ',
            },
        ),
    ]
