# Generated by Django 4.2.17 on 2024-12-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_informktp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informktp',
            name='title',
            field=models.CharField(max_length=150, verbose_name='КТП (опитовий лист)'),
        ),
        migrations.AlterField(
            model_name='informtransform',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Трансформатор (опитовий лист)'),
        ),
    ]
