# Generated by Django 4.2.17 on 2025-01-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_informktp_title_alter_informtransform_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informktp',
            options={'verbose_name': 'Опитувальний лист', 'verbose_name_plural': 'КТП - Опитувальні листи'},
        ),
        migrations.AlterModelOptions(
            name='informtransform',
            options={'verbose_name': 'Опитувальний лист', 'verbose_name_plural': 'Трансформатор - Опитувальні листи'},
        ),
    ]
