# Generated by Django 4.2.17 on 2025-01-20 16:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_informktp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informtransform',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Відео'),
        ),
        migrations.AlterField(
            model_name='transformitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
    ]
