# Generated by Django 4.2.17 on 2025-01-20 16:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_informtransform_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informtransform',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='videos/'),
        ),
    ]
