# Generated by Django 4.2.17 on 2025-01-20 16:59

import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_informtransform_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informktp',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='informtransform',
            name='file_ol',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Файл для скачування'),
        ),
        migrations.AlterField(
            model_name='transformtm',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='transformtmg',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='transformtmz',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='transformyz',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deps/img/trans.png', max_length=255, verbose_name='Зображення'),
        ),
    ]
